// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#include "ui.h"
#include "ui_helpers.h"
#include <string.h>
#include <ctype.h>


///////////////////// VARIABLES ////////////////////

#define HOLD_DELAY 100 // Delay in milliseconds for repeated actions

// Timers for each button
lv_timer_t *timer_Xplus = NULL;
lv_timer_t *timer_Xminus = NULL;
lv_timer_t *timer_Yplus = NULL;
lv_timer_t *timer_Yminus = NULL;
lv_timer_t *timer_Zplus = NULL;
lv_timer_t *timer_Zminus = NULL;



// SCREEN: ui_ActivationScreen
void ui_ActivationScreen_screen_init(void);
lv_obj_t * ui_ActivationScreen;
lv_obj_t * ui_CodeEnterTextbox;
lv_obj_t * ui_LabelScreen1;
void ui_event_CodeSubmitButton(lv_event_t * e);
lv_obj_t * ui_CodeSubmitButton;
lv_obj_t * ui_LabelSubmitButton;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;


// SCREEN: ui_MainPageScreen
void ui_MainPageScreen_screen_init(void);
lv_obj_t * ui_MainPageScreen;
void ui_event_ManuelControlButton(lv_event_t * e);
lv_obj_t * ui_ManuelControlButton;
lv_obj_t * ui_ManuelControlButtonLabel;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_SelectProgramButtonLabel;


// SCREEN: ui_SelectPropgramScreen
void ui_SelectPropgramScreen_screen_init(void);
lv_obj_t * ui_SelectPropgramScreen;
void ui_event_SelectProgramBackButton(lv_event_t * e);
lv_obj_t * ui_SelectProgramBackButton;
lv_obj_t * ui_SelectProgramBackLabel;
void search_list_event_handler(lv_event_t * e);
lv_obj_t * ui_List1;  // Define the list here
lv_obj_t * ui_TextField;
lv_obj_t * ui_Keyboard2;


// SCREEN: ui_ManuelControlScreen
void ui_ManuelControlScreen_screen_init(void);
lv_obj_t * ui_ManuelControlScreen;
void ui_event_ControlScreenBackButton(lv_event_t * e);
lv_obj_t * ui_ControlScreenBackButton;
lv_obj_t * ui_ControlScreenBackLabel;
void ui_event_ButtonYplus(lv_event_t * e);
lv_obj_t * ui_ButtonYplus;
void ui_event_ButtonXminus(lv_event_t * e);
lv_obj_t * ui_ButtonXminus;
void ui_event_ButtonYminus(lv_event_t * e);
lv_obj_t * ui_ButtonYminus;
void ui_event_ButtonXplus(lv_event_t * e);
lv_obj_t * ui_ButtonXplus;
void ui_event_ButtonZplus(lv_event_t * e);
lv_obj_t * ui_ButtonZplus;
void ui_event_ButtonZminus(lv_event_t * e);
lv_obj_t * ui_ButtonZminus;
lv_obj_t * ui_FeedRateSlider;
lv_obj_t * ui_Label7;
lv_obj_t * ui_SetZeroButton;
lv_obj_t * ui_Label8;


// SCREEN: ui_RunProgramScreen
void ui_RunProgramScreen_screen_init(void);
lv_obj_t * ui_RunProgramScreen;
void ui_event_RunProgramBackButton(lv_event_t * e);
lv_obj_t * ui_RunProgramBackButton;
lv_obj_t * ui_RunProgramBackButtonLabel;
void ui_event_ButtonYminus2(lv_event_t * e);
lv_obj_t * ui_ButtonYminus2;
void ui_event_ButtonXminus2(lv_event_t * e);
lv_obj_t * ui_ButtonXminus2;
void ui_event_ButtonXplus2(lv_event_t * e);
lv_obj_t * ui_ButtonXplus2;
void ui_event_ButtonYplus2(lv_event_t * e);
lv_obj_t * ui_ButtonYplus2;
void ui_event_ButtonZplus2(lv_event_t * e);
lv_obj_t * ui_ButtonZplus2;
void ui_event_ButtonZminus2(lv_event_t * e);
lv_obj_t * ui_ButtonZminus2;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_TextArea3;
void ui_event_MontagePunktButton(lv_event_t * e);
lv_obj_t * ui_MontagePunktButton;
lv_obj_t * ui_Label4;
void ui_event_SetZeroButton2(lv_event_t * e);
lv_obj_t * ui_SetZeroButton2;
lv_obj_t * ui_Label2;
void ui_event_RunButton(lv_event_t * e);
lv_obj_t * ui_RunButton;
lv_obj_t * ui_Label5;
lv_obj_t * ui_RunTaskLabel;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void hold_timer_cb(lv_timer_t *timer) {
    void (*action)(lv_event_t *) = (void (*)(lv_event_t *))timer->user_data;
    action(NULL); // Execute the increment/decrement function
}


void handle_timer_event(lv_event_t *e, void (*callback)(lv_timer_t *), uint32_t delay) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        button_timer = lv_timer_create(callback, delay, NULL);
    } else if (event_code == LV_EVENT_RELEASED || event_code == LV_EVENT_PRESS_LOST) {
        if (button_timer) {
            lv_timer_del(button_timer);
            button_timer = NULL;
        }
    }
}

void handle_axis_event(lv_event_t *e, void (*callback)(lv_event_t *)) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        callback(e);
    }
}



void to_lowercase_and_normalize(char *str) {
    for (int i = 0; str[i]; i++) {
        // Convert to lowercase and replace spaces with underscores
        if (str[i] == ' ') {
            str[i] = '_';
        } else {
            str[i] = tolower(str[i]);
        }
    }
}

void Increment_Y_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Increment_Y(NULL);  // Call the existing function
    }
}

void Decrement_Y_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Decrement_Y(NULL);  // Call the existing function
    }
}

void Increment_X_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Increment_X(NULL);  // Call the existing function
    }
}

void Decrement_X_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Decrement_X(NULL);  // Call the existing function
    }
}

void Increment_Z_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Increment_Z(NULL);  // Call the existing function
    }
}

void Decrement_Z_Loop(lv_timer_t * timer) {
    if (is_button_pressed) {
        Decrement_Z(NULL);  // Call the existing function
    }
}



void search_list_event_handler(lv_event_t * e)
{
    lv_obj_t * textarea = lv_event_get_target(e);
    const char * search_text_orig = lv_textarea_get_text(textarea);
    
    // Copy the search text and normalize it
    char search_text[64];
    strncpy(search_text, search_text_orig, sizeof(search_text) - 1);
    search_text[sizeof(search_text) - 1] = '\0'; // Ensure null-termination
    to_lowercase_and_normalize(search_text);

    uint32_t item_count = lv_obj_get_child_cnt(ui_List1);

    for (uint32_t i = 0; i < item_count; i++) 
    {
        lv_obj_t * item = lv_obj_get_child(ui_List1, i);
        const char * item_text_orig = lv_list_get_btn_text(ui_List1, item);
        
        // Copy item text and normalize it
        char item_text[64];
        strncpy(item_text, item_text_orig, sizeof(item_text) - 1);
        item_text[sizeof(item_text) - 1] = '\0'; // Ensure null-termination
        to_lowercase_and_normalize(item_text);

        // Check if the normalized item text contains the normalized search text
        if (strstr(item_text, search_text) != NULL) {
            lv_obj_clear_flag(item, LV_OBJ_FLAG_HIDDEN);  // Show item
        } else {
            lv_obj_add_flag(item, LV_OBJ_FLAG_HIDDEN);    // Hide item
        }
    }
}

void ui_event_CodeSubmitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainPageScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPageScreen_screen_init);
        _ui_screen_delete(&ui_ActivationScreen);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        keyboardDone(e);
    }
}
void ui_event_ManuelControlButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ManuelControlScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManuelControlScreen_screen_init);
        _ui_screen_delete(&ui_MainPageScreen);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SelectPropgramScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SelectPropgramScreen_screen_init);
        _ui_screen_delete(&ui_MainPageScreen);
    }
}
void ui_event_SelectProgramBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainPageScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPageScreen_screen_init);
        _ui_screen_delete(&ui_SelectPropgramScreen);
    }
}
void ui_event_ControlScreenBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainPageScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPageScreen_screen_init);
        _ui_screen_delete(&ui_ManuelControlScreen);
    }
}
void ui_event_ButtonYplus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Increment_Y(e);
    }
}
void ui_event_ButtonXminus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Decrement_X(e);
    }
}
void ui_event_ButtonYminus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Decrement_Y(e);
    }
}
void ui_event_ButtonXplus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Increment_X(e);
    }
}
void ui_event_ButtonZplus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Increment_Z(e);
    }
}
void ui_event_ButtonZminus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Decrement_Z(e);
    }
}

void ui_event_RunProgramBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SelectPropgramScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SelectPropgramScreen_screen_init);
        _ui_screen_delete(&ui_RunProgramScreen);
    }
}
// Event handler for X+ button
void ui_event_ButtonXplus(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Xplus == NULL) {
            timer_Xplus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Decrement_X);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Xplus != NULL) {
            lv_timer_del(timer_Xplus);
            timer_Xplus = NULL;
        }
    }
}

// Event handler for X- button
void ui_event_ButtonXminus(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Xminus == NULL) {
            timer_Xminus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Increment_X);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Xminus != NULL) {
            lv_timer_del(timer_Xminus);
            timer_Xminus = NULL;
        }
    }
}

// Event handler for Y+ button
void ui_event_ButtonYplus2(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Yplus == NULL) {
            timer_Yplus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Increment_Y);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Yplus != NULL) {
            lv_timer_del(timer_Yplus);
            timer_Yplus = NULL;
        }
    }
}

// Event handler for Y- button
void ui_event_ButtonYminus2(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Yminus == NULL) {
            timer_Yminus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Decrement_Y);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Yminus != NULL) {
            lv_timer_del(timer_Yminus);
            timer_Yminus = NULL;
        }
    }
}

// Event handler for Z+ button
void ui_event_ButtonZplus2(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Zplus == NULL) {
            timer_Zplus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Increment_Z);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Zplus != NULL) {
            lv_timer_del(timer_Zplus);
            timer_Zplus = NULL;
        }
    }
}

// Event handler for Z- button
void ui_event_ButtonZminus2(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_PRESSED) {
        if (timer_Zminus == NULL) {
            timer_Zminus = lv_timer_create(hold_timer_cb, HOLD_DELAY, (void *)Decrement_Z);
        }
    } else if (event_code == LV_EVENT_RELEASED) {
        if (timer_Zminus != NULL) {
            lv_timer_del(timer_Zminus);
            timer_Zminus = NULL;
        }
    }
}
void ui_event_MontagePunktButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        MontagePoint(e);
    }
}
void ui_event_SetZeroButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SetZeroF(e);
    }
}
void ui_event_RunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        RunProgram(e);
    }
}


///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ActivationScreen_screen_init();
    ui_MainPageScreen_screen_init();
    ui_SelectPropgramScreen_screen_init();
    ui_ManuelControlScreen_screen_init();
    ui_RunProgramScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ActivationScreen);
}
