// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#ifndef _CNC_APP_V1_UI_H
#define _CNC_APP_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"




// SCREEN: ui_ActivationScreen
void ui_ActivationScreen_screen_init(void);
extern lv_obj_t * ui_ActivationScreen;
extern lv_obj_t * ui_CodeEnterTextbox;
extern lv_obj_t * ui_LabelScreen1;
void ui_event_CodeSubmitButton(lv_event_t * e);
extern lv_obj_t * ui_CodeSubmitButton;
extern lv_obj_t * ui_LabelSubmitButton;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// SCREEN: ui_MainPageScreen
void ui_MainPageScreen_screen_init(void);
extern lv_obj_t * ui_MainPageScreen;
void ui_event_ManuelControlButton(lv_event_t * e);
extern lv_obj_t * ui_ManuelControlButton;
extern lv_obj_t * ui_ManuelControlButtonLabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_SelectProgramButtonLabel;
// SCREEN: ui_SelectPropgramScreen
void ui_SelectPropgramScreen_screen_init(void);
extern lv_obj_t * ui_SelectPropgramScreen;
void ui_event_SelectProgramBackButton(lv_event_t * e);
extern lv_obj_t * ui_SelectProgramBackButton;
extern lv_obj_t * ui_SelectProgramBackLabel;
extern lv_obj_t * ui_List1;  // Add this for the list
void search_list_event_handler(lv_event_t * e);
extern lv_obj_t * ui_TextField;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_ManuelControlScreen
void ui_ManuelControlScreen_screen_init(void);
extern lv_obj_t * ui_ManuelControlScreen;
void ui_event_ControlScreenBackButton(lv_event_t * e);
extern lv_obj_t * ui_ControlScreenBackButton;
extern lv_obj_t * ui_ControlScreenBackLabel;
void ui_event_ButtonYplus(lv_event_t * e);
extern lv_obj_t * ui_ButtonYplus;
void ui_event_ButtonXminus(lv_event_t * e);
extern lv_obj_t * ui_ButtonXminus;
void ui_event_ButtonYminus(lv_event_t * e);
extern lv_obj_t * ui_ButtonYminus;
void ui_event_ButtonXplus(lv_event_t * e);
extern lv_obj_t * ui_ButtonXplus;
void ui_event_ButtonZplus(lv_event_t * e);
extern lv_obj_t * ui_ButtonZplus;
void ui_event_ButtonZminus(lv_event_t * e);
extern lv_obj_t * ui_ButtonZminus;
extern lv_obj_t * ui_FeedRateSlider;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_SetZeroButton;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_RunProgramScreen
void ui_RunProgramScreen_screen_init(void);
extern lv_obj_t * ui_RunProgramScreen;
void ui_event_RunProgramBackButton(lv_event_t * e);
extern lv_obj_t * ui_RunProgramBackButton;
extern lv_obj_t * ui_RunProgramBackButtonLabel;
void ui_event_ButtonYminus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonYminus2;
void ui_event_ButtonXminus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonXminus2;
void ui_event_ButtonXplus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonXplus2;
void ui_event_ButtonYplus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonYplus2;
void ui_event_ButtonZplus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonZplus2;
void ui_event_ButtonZminus2(lv_event_t * e);
extern lv_obj_t * ui_ButtonZminus2;
void ui_event_MontagePunktButton(lv_event_t * e);
extern lv_obj_t * ui_MontagePunktButton;
extern lv_obj_t * ui_Label4;
void ui_event_SetZeroButton2(lv_event_t * e);
extern lv_obj_t * ui_SetZeroButton2;
extern lv_obj_t * ui_Label2;
void ui_event_RunButton(lv_event_t * e);
extern lv_obj_t * ui_RunButton;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_RunTaskLabel;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui____initial_actions0;



LV_IMG_DECLARE(ui_img_up_png);    // assets/Up.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/Left.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/Down.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/Right.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
