// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#include "ui.h"

void ui_ActivationScreen_screen_init(void)
{
    ui_ActivationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActivationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CodeEnterTextbox = lv_textarea_create(ui_ActivationScreen);
    lv_obj_set_width(ui_CodeEnterTextbox, lv_pct(25));
    lv_obj_set_height(ui_CodeEnterTextbox, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_CodeEnterTextbox, -144);
    lv_obj_set_y(ui_CodeEnterTextbox, -75);
    lv_obj_set_align(ui_CodeEnterTextbox, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_CodeEnterTextbox, "code...");
    lv_textarea_set_one_line(ui_CodeEnterTextbox, true);
    lv_obj_set_style_text_color(ui_CodeEnterTextbox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CodeEnterTextbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CodeEnterTextbox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CodeEnterTextbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelScreen1 = lv_label_create(ui_ActivationScreen);
    lv_obj_set_width(ui_LabelScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreen1, -116);
    lv_obj_set_y(ui_LabelScreen1, -142);
    lv_obj_set_align(ui_LabelScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreen1, "Please enter activation-code:");
    lv_obj_set_style_text_font(ui_LabelScreen1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CodeSubmitButton = lv_btn_create(ui_ActivationScreen);
    lv_obj_set_width(ui_CodeSubmitButton, 100);
    lv_obj_set_height(ui_CodeSubmitButton, 50);
    lv_obj_set_x(ui_CodeSubmitButton, 74);
    lv_obj_set_y(ui_CodeSubmitButton, -77);
    lv_obj_set_align(ui_CodeSubmitButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CodeSubmitButton, LV_STATE_CHECKED | LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_CodeSubmitButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CodeSubmitButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CodeSubmitButton, lv_color_hex(0x5D5B69), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_CodeSubmitButton, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_LabelSubmitButton = lv_label_create(ui_CodeSubmitButton);
    lv_obj_set_width(ui_LabelSubmitButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSubmitButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSubmitButton, -1);
    lv_obj_set_y(ui_LabelSubmitButton, 0);
    lv_obj_set_align(ui_LabelSubmitButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSubmitButton, "Submit");

    ui_Keyboard1 = lv_keyboard_create(ui_ActivationScreen);
    lv_obj_set_width(ui_Keyboard1, 748);
    lv_obj_set_height(ui_Keyboard1, 170);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 90);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_CodeSubmitButton, ui_event_CodeSubmitButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_CodeEnterTextbox);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}
