// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void keyboardDone(lv_event_t * e);
void Increment_Y(lv_event_t * e);
void Decrement_X(lv_event_t * e);
void Decrement_Y(lv_event_t * e);
void Increment_X(lv_event_t * e);
void Increment_Z(lv_event_t * e);
void Decrement_Z(lv_event_t * e);
void MontagePoint(lv_event_t * e);
void SetZeroF(lv_event_t * e);
void RunProgram(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
