// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#include "ui.h"

void ui_MainPageScreen_screen_init(void)
{
    ui_MainPageScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPageScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManuelControlButton = lv_btn_create(ui_MainPageScreen);
    lv_obj_set_height(ui_ManuelControlButton, 50);
    lv_obj_set_width(ui_ManuelControlButton, lv_pct(50));
    lv_obj_set_x(ui_ManuelControlButton, 0);
    lv_obj_set_y(ui_ManuelControlButton, -85);
    lv_obj_set_align(ui_ManuelControlButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManuelControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManuelControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManuelControlButtonLabel = lv_label_create(ui_ManuelControlButton);
    lv_obj_set_width(ui_ManuelControlButtonLabel, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ManuelControlButtonLabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ManuelControlButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManuelControlButtonLabel, "Manuel Control");
    lv_obj_set_style_text_font(ui_ManuelControlButtonLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_MainPageScreen);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_width(ui_Button3, lv_pct(50));
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SelectProgramButtonLabel = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_SelectProgramButtonLabel, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_SelectProgramButtonLabel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_SelectProgramButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectProgramButtonLabel, "Select Program");
    lv_obj_set_style_text_font(ui_SelectProgramButtonLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ManuelControlButton, ui_event_ManuelControlButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
