// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#include "ui.h"

void ui_RunProgramScreen_screen_init(void)
{
    ui_RunProgramScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RunProgramScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunProgramBackButton = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_RunProgramBackButton, 100);
    lv_obj_set_height(ui_RunProgramBackButton, 50);
    lv_obj_set_x(ui_RunProgramBackButton, -316);
    lv_obj_set_y(ui_RunProgramBackButton, 154);
    lv_obj_set_align(ui_RunProgramBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunProgramBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RunProgramBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunProgramBackButtonLabel = lv_label_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_RunProgramBackButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunProgramBackButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunProgramBackButtonLabel, -318);
    lv_obj_set_y(ui_RunProgramBackButtonLabel, 154);
    lv_obj_set_align(ui_RunProgramBackButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunProgramBackButtonLabel, "Back");

    ui_ButtonYminus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonYminus2, 91);
    lv_obj_set_height(ui_ButtonYminus2, 81);
    lv_obj_set_x(ui_ButtonYminus2, 229);
    lv_obj_set_y(ui_ButtonYminus2, 55);
    lv_obj_set_align(ui_ButtonYminus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonYminus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonYminus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonYminus2, &ui_img_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonXminus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonXminus2, 91);
    lv_obj_set_height(ui_ButtonXminus2, 81);
    lv_obj_set_x(ui_ButtonXminus2, 137);
    lv_obj_set_y(ui_ButtonXminus2, -38);
    lv_obj_set_align(ui_ButtonXminus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonXminus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonXminus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonXminus2, &ui_img_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonXplus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonXplus2, 91);
    lv_obj_set_height(ui_ButtonXplus2, 81);
    lv_obj_set_x(ui_ButtonXplus2, 322);
    lv_obj_set_y(ui_ButtonXplus2, -38);
    lv_obj_set_align(ui_ButtonXplus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonXplus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonXplus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonXplus2, &ui_img_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonYplus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonYplus2, 91);
    lv_obj_set_height(ui_ButtonYplus2, 81);
    lv_obj_set_x(ui_ButtonYplus2, 230);
    lv_obj_set_y(ui_ButtonYplus2, -132);
    lv_obj_set_align(ui_ButtonYplus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonYplus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonYplus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonYplus2, &ui_img_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonZplus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonZplus2, 91);
    lv_obj_set_height(ui_ButtonZplus2, 81);
    lv_obj_set_x(ui_ButtonZplus2, 23);
    lv_obj_set_y(ui_ButtonZplus2, -124);
    lv_obj_set_align(ui_ButtonZplus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonZplus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonZplus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonZplus2, &ui_img_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonZminus2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_ButtonZminus2, 91);
    lv_obj_set_height(ui_ButtonZminus2, 81);
    lv_obj_set_x(ui_ButtonZminus2, 23);
    lv_obj_set_y(ui_ButtonZminus2, 5);
    lv_obj_set_align(ui_ButtonZminus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonZminus2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonZminus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonZminus2, &ui_img_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MontagePunktButton = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_MontagePunktButton, 100);
    lv_obj_set_height(ui_MontagePunktButton, 50);
    lv_obj_set_x(ui_MontagePunktButton, 78);
    lv_obj_set_y(ui_MontagePunktButton, 143);
    lv_obj_set_align(ui_MontagePunktButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MontagePunktButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MontagePunktButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_MontagePunktButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 2);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "MontageP");

    ui_SetZeroButton2 = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_SetZeroButton2, 100);
    lv_obj_set_height(ui_SetZeroButton2, 50);
    lv_obj_set_x(ui_SetZeroButton2, -43);
    lv_obj_set_y(ui_SetZeroButton2, 142);
    lv_obj_set_align(ui_SetZeroButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetZeroButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetZeroButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_SetZeroButton2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Set Zero");

    ui_RunButton = lv_btn_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_RunButton, 100);
    lv_obj_set_height(ui_RunButton, 50);
    lv_obj_set_x(ui_RunButton, 203);
    lv_obj_set_y(ui_RunButton, 144);
    lv_obj_set_align(ui_RunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_RunButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Run");

    ui_RunTaskLabel = lv_label_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_RunTaskLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunTaskLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunTaskLabel, -326);
    lv_obj_set_y(ui_RunTaskLabel, -32);
    lv_obj_set_align(ui_RunTaskLabel, LV_ALIGN_CENTER);

    ui_Dropdown1 = lv_dropdown_create(ui_RunProgramScreen);
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -272);
    lv_obj_set_y(ui_Dropdown1, -140);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_RunProgramBackButton, ui_event_RunProgramBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonYminus2, ui_event_ButtonYminus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonXminus2, ui_event_ButtonXminus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonXplus2, ui_event_ButtonXplus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonYplus2, ui_event_ButtonYplus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonZplus2, ui_event_ButtonZplus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonZminus2, ui_event_ButtonZminus2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MontagePunktButton, ui_event_MontagePunktButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetZeroButton2, ui_event_SetZeroButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RunButton, ui_event_RunButton, LV_EVENT_ALL, NULL);

}
