// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: cnc-App-v1

#include "ui.h"

void ui_SelectPropgramScreen_screen_init(void)
{
    ui_SelectPropgramScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectPropgramScreen, LV_OBJ_FLAG_SCROLLABLE);   
    
    // Create a list on the screen
    ui_List1 = lv_list_create(ui_SelectPropgramScreen);
    lv_obj_set_size(ui_List1, 400, 150);  
    lv_obj_set_x(ui_List1, 144);
    lv_obj_set_y(ui_List1, -75);                  // Set list size
    lv_obj_set_align(ui_List1, LV_ALIGN_CENTER);          // Center the list

    ui_TextField = lv_textarea_create(ui_SelectPropgramScreen);
    lv_obj_set_width(ui_TextField, lv_pct(25));
    lv_obj_set_height(ui_TextField, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextField, -144);
    lv_obj_set_y(ui_TextField, -75);
    lv_obj_set_align(ui_TextField, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextField, "code...");
    lv_textarea_set_one_line(ui_TextField, true);
    lv_obj_set_style_text_color(ui_TextField, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextField, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextField, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextField, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_SelectPropgramScreen);
    lv_obj_set_width(ui_Keyboard2, 748);
    lv_obj_set_height(ui_Keyboard2, 170);
    lv_obj_set_x(ui_Keyboard2, -1);
    lv_obj_set_y(ui_Keyboard2, 90);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextField);
    // Attach event handler to the text field for search functionality
    lv_obj_add_event_cb(ui_TextField, search_list_event_handler, LV_EVENT_VALUE_CHANGED, NULL);

    ui_SelectProgramBackButton = lv_btn_create(ui_SelectPropgramScreen);
    lv_obj_set_width(ui_SelectProgramBackButton, 100);
    lv_obj_set_height(ui_SelectProgramBackButton, 50);
    lv_obj_set_x(ui_SelectProgramBackButton, -314);
    lv_obj_set_y(ui_SelectProgramBackButton, -140);
    lv_obj_set_align(ui_SelectProgramBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SelectProgramBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectProgramBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SelectProgramBackLabel = lv_label_create(ui_SelectProgramBackButton);
    lv_obj_set_width(ui_SelectProgramBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectProgramBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectProgramBackLabel, -2);
    lv_obj_set_y(ui_SelectProgramBackLabel, 1);
    lv_obj_set_align(ui_SelectProgramBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectProgramBackLabel, "Back");



    lv_obj_add_event_cb(ui_SelectProgramBackButton, ui_event_SelectProgramBackButton, LV_EVENT_ALL, NULL);

}
